<!-- Barra de navegação do topo -->
<div id="navbar-menu" class="navbar navbar-fixed-top">
<div class="navbar-inner">
  <div class="container">
    <a class="brand" href="#">Dioniso  SQL</a>
    <ul class="nav pull-right">
      <li id="fat-menu" class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Ajuda <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#help"><i class="icon-flag"></i> Conteúdo de Ajuda</a></li>
          <li><a id="link-about-license" href="javascript:;"><i class="icon-certificate"></i> Licenciamento</a></li>
          <li class="divider"></li>
          <li><a id="link-about-author" href="javascript:;">Sobre o Autor</a></li>
          <li class="divider"></li>
          <li><a id="link-about-dioniso" href="javascript:;">Sobre Dioniso</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>
</div>
<br /><br /><br /><br />
<!-- Divs para modal auxiliares -->
<div id="div-modal-loading" class="modal hide fade" style="margin-left: 23%; margin-top: 13%; width: 275px"></div>
<div id="div-modal-alert-message" class="modal hide fade">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h3>Dioniso fala:</h3>
    </div>
    <div class="modal-body" id="div-modal-alert-message-body">
        
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal">Fechar</button>
    </div>
</div>
<div id="div-modal-about" class="modal hide fade"></div>
<!--Conteúdo principal-->
<div class="container">

    <div class="masthead">
        <ul id="myTab" class="nav nav-tabs">
          <li class="active"><a href="#sql-injection" data-toggle="tab">SQL Injection</a></li>
          <li class=""><a href="#guguieie" data-toggle="tab">Gugu ié ié</a></li>
        </ul>
        <div id="myTabContent" class="tab-content">
          <div class="tab-pane well fade active in" id="sql-injection">              
              <center>
                <form id="form-ceifador" class="form-search">
                  <input id="input-target-url" type="text" class="input-xxlarge search-query" placeholder="ex.: http://www.target.com.br/detalhe-noticia.php?id=1">
                  <button id="button-ceifar" type="button" class="btn btn-danger"><i class="icon-screenshot icon-white"></i> Ceifar</button>
                </form>
              </center>
          </div>
          <div class="tab-pane well fade" id="guguieie">
              <h5>Busca página administrativa do Site</h5>
            <p>Colabore desenvolvendo este módulo! =D</p>
          </div>
        </div>
    </div>
    
    <div class="jumbotron well" id="div-status-bar" style="max-height: 275px; overflow-y: auto;">
        <p class="status-bar-title muted muted">Barra de status</p>
        <pre class="prettyprint linenums" id="pre-status-bar"><ol id="ol-status-bar" class="linenums"></ol></pre>
    </div>

    <hr>
    <ul id="div-dbs-tabs" class="nav nav-pills" style="display: none;"></ul>
    <hr />
    <div id="div-dbs-tabs-content" class="tab-content" style="display: none;"></div>    
</div>
<footer class="footer">
  <div class="container">
    <p><b>Dioniso</b> - Código licenciado sobre <a href="http://www.gnu.org/licenses/gpl-3.0.html" target="_blank">GPL v3</a>
    <p><b>&COPY;</b> - José Roniérison</a>
  </div>
</footer>

</div>


   