<?php
/**
 * Dioniso, Analysis tool safety
 *
 * LICENSE
 *
 * This source file is subject to the GNU General Public License that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0-standalone.html
 *
 * * View do modal de carregamento
 * 
 * @category   Views
 * @package    Main
 * @copyright  Copyright (c) 2013 José Roniérison <ronierison.silva@gmail.com>
 * @license    http://www.gnu.org/licenses/gpl-3.0-standalone.html GPL v3
 * @version    1.0
 * @date       17.07.2013
 */
?>

<div class="modal-header">
    <button class="close" data-dismiss="modal">&times;</button>
    <h3>Analise em andamento ..</h3>
</div>
<div class="modal-body">
    <img width="242" height="136" src="application/data/imagens/destruindo_carregamento.gif" />
</div>
<div class="modal-footer">
</div>