<div class="modal-header">
    <button class="close" data-dismiss="modal">&times;</button>
    <h3>Sobre Autores</h3>
</div>
<div class="modal-body">
    <div class="media">
      <a class="pull-left" href="#">
        <img src="application/data/imagens/JoseRonierison-96x96.jpg">
      </a>
      <div class="media-body">
        <blockquote style="margin-left: 100px;">
          <h4 class="media-heading">José Roniérison</h4>
          <small>Programador PHP/Zend</small>
          <h4 class="media-heading">Dayanne Lima</h4>
          <small>Design e apoio moral</small>
        </blockquote>
        <address style="margin-left: 110px;">
            <a>ronierison.silva@gmail.com</a><br/>
            Recife - PE, Brasil<br />
            <abbr title="Telefone">Tel.:</abbr> (81) 3481-5313<br /><br />
            <a href="https://plus.google.com/u/0/110861699425085178289/posts" target="_blank"><img height="24" width="24" src="application/data/imagens/googlePlus.jpg"></a>
        </address>        
      </div>
    </div>
    
</div>
<div class="modal-footer">
    <button class="btn" data-dismiss="modal">Fechar</button>
</div>