<?php
/**
 * Dioniso, Analysis tool safety
 *
 * LICENSE
 *
 * This source file is subject to the GNU General Public License that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0-standalone.html
 *
 * * View de sobre o projeto
 * 
 * @category   Views
 * @package    Main
 * @copyright  Copyright (c) 2013 José Roniérison <ronierison.silva@gmail.com>
 * @license    http://www.gnu.org/licenses/gpl-3.0-standalone.html GPL v3
 * @version    1.0
 * @date       17.07.2013
 */
?>

<div class="modal-header">
    <button class="close" data-dismiss="modal">&times;</button>
    <h3>Sobre Dioniso <small>Versão 1.0 Beta</small></h3>
</div>
<div class="modal-body">
    <p>O Dioniso &eacute; uma ferramenta de teste de seguran&ccedil;a em sistemas web que tenham acesso a banco de dados. O Dioniso utiliza t&eacute;cnicas de Inser&ccedil;&atilde;o SQL em par&acirc;metros da URL para testar a vunerabilidade do alvo.</p>
    <p>O Dioniso foi desenvolvido sobre licen&ccedil;a <a target="_blank" href="http://www.gnu.org/licenses/gpl-3.0.html">GPL v3</a> na lingagem <a target="_blank" href="http://php.net">PHP</a> modelado com Framework <a target="_blank" href="http://www.zend.com/en/">Zend V1</a> e desenhado utilizando o <a target="_blank" href="http://twitter.github.io/bootstrap/index.html">Twitte Boostrap</a>.</p>
    <ul>
      <li>Versão: 1.0 Beta</li>
    </ul>
</div>
<div class="modal-footer">
    <button class="btn" data-dismiss="modal">Fechar</button>
</div>