<div class="modal-header">
    <button class="close" data-dismiss="modal">&times;</button>
    <h3>Sobre Dioniso <small>Versão 1.0</small></h3>
</div>
<div class="modal-body">
    <p>O Dioniso é uma ferramente de teste de segurança em sistemas web que tenham acesso a banco de dados. O Dioniso utiliza técnicas de Inserção SQL em parâmetros da URL para testar a vunerabilidade do alvo.</p>
    <p>O Dioniso foi desenvolvido sobre licensa <a target="_blank" href="http://www.gnu.org/licenses/gpl-3.0.html">GPL v3</a> na lingagem <a target="_blank" href="http://php.net">PHP</a> modelado com Framework <a target="_blank" href="http://www.zend.com/en/">Zend</a> e desenhado utilizando o <a target="_blank" href="http://twitter.github.io/bootstrap/index.html">Twitte Boostrap</a>.</p>
    <ul>
      <li>Versão: 1.0</li>
    </ul>
</div>
<div class="modal-footer">
    <button class="btn" data-dismiss="modal">Fechar</button>
</div>