<?php
$this->jQuery()
     ->setLocalPath('public/jquery/Jquery.js')
     //->setUiLocalPath('public/jquery/js/jquery-ui-1.8.20.custom.min.js')
     //->addStylesheet('public/jquery/css/ui-lightness/jquery-ui-1.8.20.custom.css')
     //->addJavascriptFile('public/jquery/js/jquery.ui.datepicker-pt-BR.js') <script type="text/javascript" src="public/jquery/Jquery.js"></script>
     //->addJavascriptFile('public/jquery/plugins/jquery.maskedinput-1.1.4.pack.js');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="content-style-type" content="text/css" />
<meta http-equiv="content-language" content="pt-br" />
<title><? echo $this->titulo;  ?></title>    

<?php
    $this->jQuery()->enable();
    /*
     * Força a entrada do script JQuery
     *
     * Echo no Helper Zendx_JQuery
     * 
     * **** Dá echo somente nos scripts externos e css's do ZendX
     */
    echo $this->jQuery();
    ?><link href="public/twitter-bootstrap-v2.0.3/css/bootstrap.css" rel="stylesheet" type="text/css" title="Bootstrap" /><?
    /**
     * Introduz todos os arquivos de javascript informados no controlador no caberçalho
     *
     * @type        array
     * @elements    type=string | define tipo do script informado
     * @elements    src=string  | caminho para incluir o arquivos
     */

    /*------------------------------------
     * Este elemente está sendo inserido aqui por força de algum erro no processamento do zend.
     * Suponho que o repasse entre a view e o dispachado está sendo lento, não dando tempo para o 
     * corpo html carregar os objetos da classe modal.
     */
    ?><script type="text/javascript" src="public/twitter-bootstrap-v2.0.3/js/bootstrap-modal.js"></script><?
    if(is_array($this->headJs)){
        foreach($this->headJs as $javascript){
            $type = (isset($javascript['type'])? $javascript['type'] : 'text/javascript');
            $code = (isset($javascript['code'])? $javascript['code'] : '');
            $src = (isset($javascript['src'])? 'src="'.$javascript['src'].'"' : '');
            echo '<script type="'.$type.'" '.$src.'>'.$code.'</script>';
        }
    }

    /**
     * Introduz todos os arquivos de css informados no controlador
     *
     * @type        array
     * @elements    href=string     | caminho para incluir o arquivos
     * @elements    rel=string      | define rel (stylesheet, alternate stylesheet)
     * @elements    type=string     | define tipo do script css informado
     * @elements    titulo=string   | define título
     */
    if(is_array($this->css)){
        foreach($this->css as $css){
            $rel = (isset($css['rel'])? $css['rel'] : 'stylesheet');
            $type = (isset($css['type'])? $css['type'] : 'text/css');
            $title = (isset($css['title'])? 'title="'.$css['title'].'"' : '');

            echo '<link href="'.$css['href'].'" rel="'.$rel.'" type="'.$type.'" '.$title.'/>';
        }
    }

?>

<?= $this->layout()->content; ?>
    
<?php
/*
     * Força o scripts onloads a serem dispejados na após scripts
     */
    echo $this->jQuery()->_renderExtras();
    /**
     * Introduz todos os arquivos de javascript informados no controlador
     *
     * @type        array
     * @elements    type=string | define tipo do script informado
     * @elements    src=string  | caminho para incluir o arquivos
     */
    if(is_array($this->js)){
        foreach($this->js as $javascript){
            $type = (isset($javascript['type'])? $javascript['type'] : 'text/javascript');
            $code = (isset($javascript['code'])? $javascript['code'] : '');
            $src = (isset($javascript['src'])? 'src="'.$javascript['src'].'"' : '');
            echo '
                <script type="'.$type.'" '.$src.'>'.$code.'</script>';
        }
    }
?>


