<?php
/**
 * Dioniso, Analysis tool safety
 *
 * LICENSE
 *
 * This source file is subject to the GNU General Public License that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0-standalone.html
 *
 * Arquivo base de redenrização
 * 
 * @category   Views
 * @package    Main
 * @copyright  Copyright (c) 2013 José Roniérison <ronierison.silva@gmail.com>
 * @license    http://www.gnu.org/licenses/gpl-3.0-standalone.html GPL v3
 * @version    1.0
 * @date       15.07.2013
 */



?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="content-style-type" content="text/css" />
<meta http-equiv="content-language" content="pt-br" />
<title><?= $this->titulo;  ?></title>    
<link href="public/twitter-bootstrap-v2.0.3/css/bootstrap.css" rel="stylesheet" type="text/css" title="Bootstrap" /><?


    /**
     * Introduz todos os arquivos de css informados no controlador
     *
     * @type        array
     * @elements    href=string     | caminho para incluir o arquivos
     * @elements    rel=string      | define rel (stylesheet, alternate stylesheet)
     * @elements    type=string     | define tipo do script css informado
     * @elements    titulo=string   | define título
     */
    if(is_array($this->css)){
        foreach($this->css as $css){
            $rel = (isset($css['rel'])? $css['rel'] : 'stylesheet');
            $type = (isset($css['type'])? $css['type'] : 'text/css');
            $title = (isset($css['title'])? 'title="'.$css['title'].'"' : '');

            echo '<link href="'.$css['href'].'" rel="'.$rel.'" type="'.$type.'" '.$title.'/>';
        }
    }
    
?>
<script type="text/javascript" src="public/jquery/Jquery.js"></script>
<script type="text/javascript" src="public/twitter-bootstrap-v2.0.3/js/bootstrap-transition.js"></script>
<script type="text/javascript" src="public/twitter-bootstrap-v2.0.3/js/bootstrap-modal.js"></script>
<?= $this->layout()->content; ?>
    
<?php
    /**
     * Introduz todos os arquivos de javascript informados no controlador
     *
     * @type        array
     * @elements    type=string | define tipo do script informado
     * @elements    src=string  | caminho para incluir o arquivos
     */
    if(is_array($this->js)){
        foreach($this->js as $javascript){
            $type = (isset($javascript['type'])? $javascript['type'] : 'text/javascript');
            $code = (isset($javascript['code'])? $javascript['code'] : '');
            $src = (isset($javascript['src'])? 'src="'.$javascript['src'].'"' : '');
            echo '
                <script type="'.$type.'" '.$src.'>'.$code.'</script>';
        }
    }
    

?>


